apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-api-server
          env:
            - name: OBJECTSTORECONFIG_BUCKETNAME
              valueFrom: 
                configMapKeyRef:
                  name: gcp-configs
                  key: bucket_name
            - name: DBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credential
                  key: password
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cloudsqlproxy
spec:
  template:
    spec:
      containers:
        - name: cloudsqlproxy
          env:
            - name: CLOUD_SQL_INSTANCE_CONNECTION_NAME
              valueFrom: 
                configMapKeyRef:
                  name: gcp-configs
                  key: sql_connection_name
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credential
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    {
    namespace: $(NAMESPACE),
    executorImage: gcr.io/ml-pipeline/argoexec:v2.3.0-license-compliance,
    artifactRepository:
    {
        s3: {
            bucket: $(BUCKET),
            keyPrefix: artifacts,
            endpoint: minio-service.$(NAMESPACE):9000,
            insecure: true,
            accessKeySecret: {
                name: mlpipeline-minio-artifact,
                key: accesskey
            },
            secretKeySecret: {
                name: mlpipeline-minio-artifact,
                key: secretkey
            }
        }
    }
    }